/*
 * generated by Xtext 2.25.0
 */
package at.constantly;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EntitiesStandaloneSetup extends EntitiesStandaloneSetupGenerated {

	public static void doSetup() {
		new EntitiesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
