/*
 * generated by Xtext 2.25.0
 */
package at.constantly.ide;

import at.constantly.EntitiesRuntimeModule;
import at.constantly.EntitiesStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EntitiesIdeSetup extends EntitiesStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EntitiesRuntimeModule(), new EntitiesIdeModule()));
	}
	
}
