/*
 * generated by Xtext 2.25.0
 */
package at.constantly;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntitiesRuntimeModule extends AbstractEntitiesRuntimeModule {
}
